version: '3'

volumes:
  app-postgres-data:
    driver: local

services:
  app:
    user: ${APP_UID}:${APP_GID}
    container_name: ${APP_NAME}-app
    image: webdevops/php-nginx:8.2-alpine
    volumes:
      - ./project:/app
    working_dir: /app
    ports:
      - ${APP_PORT}:80
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_MEMORY_LIMIT=${APP_MEMORY_LIMIT}
      - php.opcache.enable_cli=1

  postgres:
    container_name: ${APP_NAME}-postgres
    image: postgres:16-alpine
    volumes:
      - app-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432

  redis:
    container_name: ${APP_NAME}-redis
    image: redis:5.0
    command: --appendonly no
    ports:
      - ${REDIS_PORT}:6379

  worker:
    container_name: ${APP_NAME}-worker
    build: environment/docker/worker/.
    volumes:
      - ./project:/app
    environment:
      - PHP_MEMORY_LIMIT=${WORKER_MEMORY_LIMIT}