version: '3'

services:
  app:
    user: ${APP_UID}:${APP_GID}

  postgres-test:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_TEST_DB}
      - POSTGRES_USER=${POSTGRES_TEST_USER}
      - POSTGRES_PASSWORD=${POSTGRES_TEST_PASSWORD}
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - ${POSTGRES_TEST_PORT}:5432

  mailcatcher:
    container_name: ${APP_NAME}-mailcatcher
    image: schickling/mailcatcher
    ports:
      - ${MAILCATCHER_PORT}:1080
      - 1025:1025