name: Styleguide Check (Pint)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
      - feature/**
      - hotfix/**
      - release/**
      - refactor/**
    paths:
      - '**.php'
      - 'phpunit.xml'
      - '.github/workflows/style.yml'
      - 'composer.lock'

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@2.0.0
        with:
          preset: laravel
          verboseMode: true
          testMode: true
          configPath: "project/pint.json"
          pintVersion: 1.13.10